### Embedding 계층 구현

In [8]:
import numpy as np
W = np.arange(21).reshape(7, 3)
W

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [9]:
word_idx = np.array([0,0,0,0,0,1,0]) 
print(word_idx.shape)
word_vec = np.dot(word_idx, W)  # (7,)(7,3)
word_vec

(7,)


array([15, 16, 17])

In [10]:
W[5]

array([15, 16, 17])

In [11]:
word_idx = np.array([[1,0,0,0,0,0,0],
                     [0,1,0,0,0,0,0],
                     [0,0,1,0,0,0,0]]) 
print(word_idx.shape)
word_vec = np.dot(word_idx, W)  # (3,7)(7,3)
word_vec

(3, 7)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
idx = np.array([0,1,2])
W[idx]  # W[[0,1,2]]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
class Embedding:
    def __init__(self, W):
        self.params = [W]
        self.grads = [np.zeros_like(W)]
        self.idx = None

    def forward(self, idx):
        W, = self.params
        self.idx = idx
        out = W[idx]
        return out
    
    def backward(self, dout):
        dW, = self.grads
        dW[...] = 0
        dW[self.idx] = dout
        return None

In [30]:
W = np.arange(21).reshape(7, 3)
embed = Embedding(W)
out = embed.forward([0,1,2,0])
print(embed.idx)
print(out)
dout = np.array([[1,1,1],[2,2,2],[3,3,3],[4,4,4]])
embed.backward(dout)
print(embed.grads)

[0, 1, 2, 0]
[[0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]]
[array([[4, 4, 4],
       [2, 2, 2],
       [3, 3, 3],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])]


In [31]:
class Embedding:
    def __init__(self, W):
        self.params = [W]
        self.grads = [np.zeros_like(W)]
        self.idx = None

    def forward(self, idx):
        W, = self.params
        self.idx = idx
        out = W[idx]
        return out

    def backward(self, dout):
        dW, = self.grads
        dW[...] = 0
        for i, word_id in enumerate(self.idx):
            dW[word_id] += dout[i]
        return None

In [32]:
W = np.arange(21).reshape(7, 3)
embed = Embedding(W)
out = embed.forward([0,1,2,0])
print(embed.idx)
print(out)
dout = np.array([[1,1,1],[2,2,2],[3,3,3],[4,4,4]])
embed.backward(dout)
print(embed.grads)

[0, 1, 2, 0]
[[0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]]
[array([[5, 5, 5],
       [2, 2, 2],
       [3, 3, 3],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])]


In [10]:
class Embedding:
    def __init__(self, W):
        self.params = [W]
        self.grads = [np.zeros_like(W)]
        self.idx = None

    def forward(self, idx):
        W, = self.params
        self.idx = idx
        out = W[idx]
        return out

    def backward(self, dout):
        dW, = self.grads
        dW[...] = 0
        np.add.at(dW, self.idx, dout)
        return None

In [33]:
W = np.arange(21).reshape(7, 3)
embed = Embedding(W)
out = embed.forward([0,1,2,0])
print(embed.idx)
print(out)
dout = np.array([[1,1,1],[2,2,2],[3,3,3],[4,4,4]])
embed.backward(dout)
print(embed.grads)

[0, 1, 2, 0]
[[0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]]
[array([[5, 5, 5],
       [2, 2, 2],
       [3, 3, 3],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])]
