# 신경망의 학습

## Repeat 노드

In [7]:
import numpy as np

D, N = 8, 7
x = np.random.rand(1,D)
print(x.shape)
y = np.repeat(x, N, axis=0)
print(y.shape)
dy = np.random.rand(N, D)
print(dy.shape)
dx = np.sum(dy, axis=0, keepdims=True)
print(dx.shape)

(1, 8)
(7, 8)
(7, 8)
(1, 8)


In [8]:
dx

array([[3.22154574, 3.38815829, 3.77374445, 3.39201497, 2.70230468,
        4.42315302, 3.4448541 , 2.60725579]])

## Sum 노드

In [10]:
import numpy as np

D, N = 8, 7
x = np.random.rand(N, D)
print(x.shape)
y = np.sum(x, axis=0, keepdims=True)
print(y.shape)

dy = np.random.rand(1, D)
print(dy.shape)
dx = np.repeat(dy, N, axis=0)
print(dx.shape)

(7, 8)
(1, 8)
(1, 8)
(7, 8)


In [11]:
dx

array([[0.82713433, 0.16996966, 0.90020129, 0.25318446, 0.41110565,
        0.72405875, 0.56162708, 0.5978607 ],
       [0.82713433, 0.16996966, 0.90020129, 0.25318446, 0.41110565,
        0.72405875, 0.56162708, 0.5978607 ],
       [0.82713433, 0.16996966, 0.90020129, 0.25318446, 0.41110565,
        0.72405875, 0.56162708, 0.5978607 ],
       [0.82713433, 0.16996966, 0.90020129, 0.25318446, 0.41110565,
        0.72405875, 0.56162708, 0.5978607 ],
       [0.82713433, 0.16996966, 0.90020129, 0.25318446, 0.41110565,
        0.72405875, 0.56162708, 0.5978607 ],
       [0.82713433, 0.16996966, 0.90020129, 0.25318446, 0.41110565,
        0.72405875, 0.56162708, 0.5978607 ],
       [0.82713433, 0.16996966, 0.90020129, 0.25318446, 0.41110565,
        0.72405875, 0.56162708, 0.5978607 ]])

## MatMul 

In [12]:
class MatMul:
    def __init__(self, W):
        self.params = [W]
        self.grads = [np.zeros_like(W)]
        self.x = None

    def forward(self, x):
        W, = self.params
        out = np.dot(x, W)
        self.x = x
        return out

    def backward(self, dout):
        W, = self.params
        dx = np.dot(dout, W.T)
        dW = np.dot(self.x.T, dout)
        self.grads[0][...] = dW
        return dx

In [14]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a = b
print(a)
b[0] = 10
print(a)
id(a) == id(b)
print(id(a), id(b))

[4 5 6]
[10  5  6]
2337526680272 2337526680272


In [16]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a[...] = b
print(a)
b[0] = 10
print(a)
id(a) == id(b)
print(id(a), id(b))

[4 5 6]
[4 5 6]
2337526669680 2337523138272


## 시그모이드 계층

In [32]:
class Sigmoid:
    def __init__(self):
        self.params, self.grads = [], []
        self.out = None

    def forward(self, x):
        out = 1 / (1 + np.exp(-x))
        self.out = out
        return out

    def backward(self, dout):
        dx = dout * (1.0 - self.out) * self.out
        return dx

## Affine 계층

In [33]:
class Affine:
    def __init__(self, W, b):
        self.params = [W, b]
        self.grads = [np.zeros_like(W), np.zeros_like(b)]
        self.x = None

    def forward(self, x):
        W, b = self.params
        out = np.dot(x, W) + b
        self.x = x
        return out

    def backward(self, dout):
        W, b = self.params
        dx = np.dot(dout, W.T)
        dW = np.dot(self.x.T, dout)
        db = np.sum(dout, axis=0)

        self.grads[0][...] = dW
        self.grads[1][...] = db
        return dx

## Softmax with Loss 계층

In [34]:
class SoftmaxWithLoss:
    def __init__(self):
        self.params, self.grads = [], []
        self.y = None  # softmax의 출력
        self.t = None  # 정답 레이블

    def forward(self, x, t):
        self.t = t
        self.y = softmax(x)

        # 정답 레이블이 원핫 벡터일 경우 정답의 인덱스로 변환
        if self.t.size == self.y.size:
            self.t = self.t.argmax(axis=1)

        loss = cross_entropy_error(self.y, self.t)
        return loss

    def backward(self, dout=1):
        batch_size = self.t.shape[0]

        dx = self.y.copy()
        dx[np.arange(batch_size), self.t] -= 1
        dx *= dout
        dx = dx / batch_size

        return dx

## 가중치 갱신

In [35]:
class SGD:
    '''
    확률적 경사하강법(Stochastic Gradient Descent)
    '''
    def __init__(self, lr=0.01):
        self.lr = lr
        
    def update(self, params, grads):
        for i in range(len(params)):
            params[i] -= self.lr * grads[i]