In [3]:
import numpy as np
from numpy.linalg import svd

A = np.array([[3, -1], [1, 3], [1, 1]])
print(A.shape)
U, S, VT = svd(A)

(3, 2)


In [4]:
U

array([[-4.08248290e-01,  8.94427191e-01, -1.82574186e-01],
       [-8.16496581e-01, -4.47213595e-01, -3.65148372e-01],
       [-4.08248290e-01, -2.06937879e-16,  9.12870929e-01]])

In [5]:
S

array([3.46410162, 3.16227766])

In [6]:
VT

array([[-0.70710678, -0.70710678],
       [ 0.70710678, -0.70710678]])

In [7]:
print(S)
temp = np.diag(S, 1) 
print(temp)
temp = temp[:, 1:]
print(temp)

[3.46410162 3.16227766]
[[0.         3.46410162 0.        ]
 [0.         0.         3.16227766]
 [0.         0.         0.        ]]
[[3.46410162 0.        ]
 [0.         3.16227766]
 [0.         0.        ]]


In [9]:
print(A)
print(U @ np.diag(S, 1)[:, 1:] @ VT)

[[ 3 -1]
 [ 1  3]
 [ 1  1]]
[[ 3. -1.]
 [ 1.  3.]
 [ 1.  1.]]


In [157]:
U2, S2, VT2 = svd(A, full_matrices=False)

In [158]:
U2

array([[-4.08248290e-01,  8.94427191e-01],
       [-8.16496581e-01, -4.47213595e-01],
       [-4.08248290e-01, -2.06937879e-16]])

In [159]:
S2

array([3.46410162, 3.16227766])

In [160]:
VT2

array([[-0.70710678, -0.70710678],
       [ 0.70710678, -0.70710678]])

In [161]:
np.diag(S2) 

array([[3.46410162, 0.        ],
       [0.        , 3.16227766]])

In [162]:
U2 @ np.diag(S2) @ VT2

array([[ 3., -1.],
       [ 1.,  3.],
       [ 1.,  1.]])